"""Initial migration

Revision ID: 8f7774e7a89e
Revises: 05e5136e88f5
Create Date: 2025-01-30 01:24:35.420785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7774e7a89e'
down_revision = '05e5136e88f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('day_week', sa.Integer(), nullable=True),
    sa.Column('day_month', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    # ### end Alembic commands ###
